name: Submission MLOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari GitHub
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. Install Library
    - name: Install Dependencies
      working-directory: ./preprocessing
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan Preprocessing
    - name: Run Preprocessing
      working-directory: ./preprocessing
      run: python automate_Khazel-Hayfa.py
    
    # 5. Simpan Output agar bisa didownload
    - name: Upload Preprocessed Data
      uses: actions/upload-artifact@v4
      with:
        name: hasil-preprocessing
        path: preprocessing/E Commerce Dataset_preprocessing.csv